### ISSUE TITLE
Yara 3 Compiler Errors

### ISSUE THREAD

**Issue by ceelias** [BayshoreNetworks/yextend#1]
make  all-am
make[1]: Entering directory `/home/chris/Bayshore/yextend'
gcc -DHAVE_CONFIG_H -I.   -I.  -g -O2 -MT bayshore_yara_wrapper.o -MD -MP -MF .deps/bayshore_yara_wrapper.Tpo -c -o bayshore_yara_wrapper.o bayshore_yara_wrapper.c
bayshore_yara_wrapper.c: In function ‘bayshore_yara_preprocess_rules’:
bayshore_yara_wrapper.c:286:4: warning: passing argument 2 of ‘yr_compiler_set_callback’ from incompatible pointer type [enabled by default]
In file included from /usr/local/include/yara.h:22:0,
                 from bayshore_yara_wrapper.h:27,
                 from bayshore_yara_wrapper.c:28:
/usr/local/include/yara/compiler.h:138:13: note: expected ‘YR_COMPILER_CALLBACK_FUNC’ but argument is of type ‘void (*)(int,  const char *, int,  const char *)’
bayshore_yara_wrapper.c: In function ‘bayshore_yara_wrapper_api’:
bayshore_yara_wrapper.c:480:4: warning: passing argument 2 of ‘yr_compiler_set_callback’ from incompatible pointer type [enabled by default]
In file included from /usr/local/include/yara.h:22:0,
                 from bayshore_yara_wrapper.h:27,
                 from bayshore_yara_wrapper.c:28:
/usr/local/include/yara/compiler.h:138:13: note: expected ‘YR_COMPILER_CALLBACK_FUNC’ but argument is of type ‘void (*)(int,  const char *, int,  const char *)’
mv -f .deps/bayshore_yara_wrapper.Tpo .deps/bayshore_yara_wrapper.Po
g++  -g -O2   -o yextend filedissect.o wrapper.o bayshore_content_scan.o filedata.o main.o zl.o bayshore_yara_wrapper.o  -lpcrecpp -lz -lyara -lcrypto -larchive 
make[1]: Leaving directory `/home/chris/Bayshore/yextend'

**Comment by garbagecat** [comment]
hmm, is this a regression? Did you update to a newer version of the yara
code?

**Comment by ceelias** [comment]
Yes these are the errors that are given with the latest version of Yara. Dre asked me to post my results here.

**Comment by dre** [comment]
So it seems some functions we call on the yara side have changed (they now have an extra argument). Will fix, this means that yextend 1.2 will only work with yara 3.3 and above.

**Comment by garbagecat** [comment]
You probably ought to tell the Yara guy that it's not nice to break his
users's code.

Another fucked up thing is that if you're using C instead of C++, there's
no compiler-level breakage. Your code just won't work.

**Comment by dre** [comment]
Chris, try again with version 1.2 of yextend.
