### ISSUE TITLE
Clean up parent/child output

### ISSUE THREAD

**Issue by dre** [BayshoreNetworks/yextend#10]
When running yextend against a file that is not an archive the output (when there is a hit) looks like this:

...
Scan Type: Yara Scan (PDF - Raw data)
Parent File Name: test_files/lipsum.txt.pdf
Child File Name: test_files/lipsum.txt.pdf
File Signature (MD5): ec650a3a287603d350718b74716aee1c
...

Since the filename is the same for parent and child it makes no sense to output them both so only output:

File Name: X

when the actual file name (and path) are identical values. Otherwise the output should stay the same.

**Comment by spal-bayshorenetworks** [comment]
Now we don't show the same file name for parent and child.
