### ISSUE TITLE
Feature request: Machine-readable output (e.g. JSON)

### ISSUE THREAD

**Issue by austinbyers** [BayshoreNetworks/yextend#13]
First, let me say - what a great tool!

We are thinking of integrating `yextend` into [BinaryAlert](https://binaryalert.io) so that users can analyze archives with all of their YARA rules. Unfortunately, as far as I can tell (looking at v1.5), there is no machine-readable output, just text printed to stdout.

Would it be possible to get the output in JSON format?

Even better (but probably more difficult) - if this could be a Python package (`pip install yextend`), that would be amazing. Because then the match results would be available to a Python application (like BinaryAlert)

**Comment by dre** [comment]
Hey Austin, Thx for the note. Output in JSON format is a great idea and we can certainly get done. As for the py package that would take a bit longer due to our current workload. But it is also a great idea and I would like to get that done, it will just take us a bit longer. Let me get something in the develop branch for the JSON output in the next few days and I will let you know so you guys can take a look. Happy Thanksgiving to you all - Dre

**Comment by dre** [comment]
So if you are ready to try this out pull the latest from the develop branch (https://github.com/BayshoreNetworks/yextend/tree/develop) and let me know if you find this approach useful. Basically what gets spit out to stdout (when using -j) is the resulting JSON. Here is an example:

./run_yextend -r test_rulesets/BAYSHORE_Officex1.yar -t test_files/Lorem-winlogon.docx.bz2 -j
[
    {
        "file_name": "test_files/Lorem-winlogon.docx.bz2",
        "file_signature_MD5": "26b485701d6a47618a7f915aa7a38045",
        "file_size": 208940,
        "yara_ruleset_file_name": "test_rulesets/BAYSHORE_Officex1.yar",
        "yara_scan_results_1": {
            "child_file_name": "word/document.xml",
            "file_signature_MD5": "9d58972d9a528da89c971597e4aa1844",
            "parent_file_name": "test_files/Lorem-winlogon.docx",
            "scan_type": "Yara Scan (Office Open XML)  inside BZIP2 Archive file"
        },
        "yara_scan_results_2": {
            "child_file_name": "word/embeddings/oleObject1.bin",
            "file_signature_MD5": "27250593fccbfb679320a74be9459d17",
            "parent_file_name": "test_files/Lorem-winlogon.docx",
            "scan_type": "Yara Scan (Microsoft Office document (DOC PPT XLS)) embedded in an Office Open XML file",
            "yara_results": {
                "maldoc_suspicious_strings": {
                    "description": "suspicious marco action",
                    "detected offsets": [
                        "0x12231:$a02",
                        "0x135c5:$a03",
                        "0x55dc7:$a03",
                        "0x5f1e2:$a03",
                        "0x55db9:$a09",
                        "0x5f1d5:$a09",
                        "0x55e31:$a12",
                        "0x1037d:$a15"
                    ],
                    "hit_count": "8"
                }
            }
        },
        "yara_scan_results_3": {
            "child_file_name": "word/embeddings/oleObject1.bin",
            "file_signature_MD5": "6674f1535a94304e58f26d06f348190d",
            "parent_file_name": "test_files/Lorem-winlogon.docx",
            "scan_type": "Yara Scan (Office Open XML)  inside BZIP2 Archive file"
        }
    }
]

**Comment by austinbyers** [comment]
Wow, fast turnaround! Thanks! Is the `description` an example of YARA rule metadata? Because we definitely will need the rule metadata so that analysts can more easily triage alerts. Other nice-to-haves (not required):

1. It would be useful if there were a top-level key `yara_matches_found = true` or similar so that the entire JSON does not have to be traversed to see if there are any `yara_results` (BinaryAlert triggers an alert only if a YARA match is found)
2. I really like the tree view showing all the nested files (the OMEGA section in normal output). I wonder if there's some way to include that? Instead of parent/child keys, maybe the structure is built into the JSON?

The structure might then look like this:

```json
[
   {
      "yara_matches_found": true,
      "yara_ruleset_file_name": "test_rulesets/BAYSHORE_Officex1.yar",

      "scan_results": {
         "file_name": "test_files/Lorem-winlogon.docx.bz2",
         "file_signature_MD5": "26b485701d6a47618a7f915aa7a38045",
         "file_size": 208940,
         "children": [
            {
               "file_name": "word/document.xml",
               "file_signature_MD5": "9d58972d9a528da89c971597e4aa1844",
               "file_size": 123,
               "scan_type": "Yara Scan (Office Open XML) inside BZIP2 Archive file"
            },
            {
               "file_name": "word/embeddings/oleObject1.bin",
               "file_signature_MD5": "9d58972d9a528da89c971597e4aa1844",
               "file_size": 123,
               "scan_type": "Yara Scan (Microsoft Office document (DOC PPT XLS)) embedded in an Office Open XML file",
               "yara_results": {
                  "maldoc_suspicious_strings": {
                     "description": "suspicious macro action",
                     "offsets": [
                        "0x12231:$a02",
                        "0x135c5:$a03",
                        "0x55dc7:$a03",
                        "0x5f1e2:$a03",
                        "0x55db9:$a09",
                        "0x5f1d5:$a09",
                        "0x55e31:$a12",
                        "0x1037d:$a15"
                     ],
                  }
               }
            },
            {
               "file_name": "word/embeddings/oleObject1.bin",
               "file_signature_MD5": "6674f1535a94304e58f26d06f348190d",
               "file_size": 345,
               "scan_type": "Yara Scan (Office Open XML) inside BZIP2 Archive file"
            }
         ]
      }
   }
]
```

**Comment by dre** [comment]
So here is output with structure built into it. This is from the develop branch right now and the structured output is generated by using the -a switch in conjunction with the -j switch on run_yextend

./run_yextend -r test_rulesets/BAYSHORE_Officex1.yar -t test_files/Lorem-winlogon.docx.bz2 -j -a
[
    {
        "yara_matches_found": true, 
        "scan_results": [
            {
                "yara_matches_found": false, 
                "file_name": "test_files/Lorem-winlogon.docx", 
                "file_size": 210193, 
		"file_signature_MD5": "d8f0fab30eae91687c0d80f8dd08218f”,
                "children": [
                    {
                        "yara_matches_found": false, 
                        "file_size": 29639, 
                        "file_name": "word/document.xml", 
                        "file_signature_MD5": "9d58972d9a528da89c971597e4aa1844", 
                        "scan_type": "Yara Scan (Office Open XML)  inside BZIP2 Archive file"
                    }, 
                    {
                        "yara_matches_found": true, 
                        "file_name": "word/embeddings/oleObject1.bin", 
                        "scan_type": "Yara Scan (Microsoft Office document (DOC PPT XLS)) embedded in an Office Open XML file", 
                        "yara_results": {
                            "maldoc_suspicious_strings": {
                                "description": "suspicious marco action", 
                                "hit_count": "8", 
                                "offsets": [
                                    "0x12231:$a02", 
                                    "0x135c5:$a03", 
                                    "0x55dc7:$a03", 
                                    "0x5f1e2:$a03", 
                                    "0x55db9:$a09", 
                                    "0x5f1d5:$a09", 
                                    "0x55e31:$a12", 
                                    "0x1037d:$a15"
                                ]
                            }
                        }, 
                        "file_size": 392192, 
                        "file_signature_MD5": "27250593fccbfb679320a74be9459d17"
                    }, 
                    {
                        "yara_matches_found": false, 
                        "file_size": 8, 
                        "file_name": "word/embeddings/oleObject1.bin", 
                        "file_signature_MD5": "6674f1535a94304e58f26d06f348190d", 
                        "scan_type": "Yara Scan (Office Open XML)  inside BZIP2 Archive file"
                    }
                ], 
            }
        ], 
        "file_name": "test_files/Lorem-winlogon.docx.bz2", 
        "yara_ruleset_file_name": "test_rulesets/BAYSHORE_Officex1.yar", 
        "file_size": 208940,
	"file_signature_MD5": "26b485701d6a47618a7f915aa7a38045”,
        "children": [
            {
                "yara_matches_found": false, 
                "file_size": 210193, 
                "file_name": "test_files/Lorem-winlogon.docx", 
                "file_signature_MD5": "d8f0fab30eae91687c0d80f8dd08218f"
            }
        ],
    }
]

Let me know if this meets the need and we will cut a release - Dre

**Comment by austinbyers** [comment]
Yeah, that looks great! Thanks so much! Is the `-a` and `-j` switch available from the `yextend` binary or only the `run_yextend` wrapper? BinaryAlert will be bundling just the binary

**Comment by austinbyers** [comment]
Although it doesn't have to, the wrapper script is fine. I imagine it's easier to do the advanced output in Python rather than C :)

**Comment by dre** [comment]
Well, real work got in the way ( :-) ) so we did what we could. We got slammed with work right after Thanksgiving and to do the transformation in c++ would just take too long. So if the wrapper script is cool for now I will close this out and cut a build.

**Comment by austinbyers** [comment]
That's perfect, thanks so much! Really appreciate it, this will let us build `yextend` into the next BinaryAlert version before the end of the year
