### ISSUE TITLE
YARA version is not read correctly in v1.5 - Need new release

### ISSUE THREAD

**Issue by austinbyers** [BayshoreNetworks/yextend#14]
Yextend thinks the YARA version is 0.0 instead of 3.7.0 when compiled on Amazon Linux:

```
$ ./run_yextend test.yara test.yara

Version issue: yextend version 1.4+ will not run with yara versions below 3.4

Your env has yextend version 1.4
Your env has yara version 0.0
```

This is in the official [1.5 release](https://github.com/BayshoreNetworks/yextend/releases/tag/1.5). The problem has been fixed as of the latest commit to master, but there hasn't been a new release in over a year.

Can we get a new stable release? Thanks!

**Comment by dre** [comment]
I will release 1.6 in a few days, gonna put some cycles into the JSON output. Yara's version output format changed and that is the reason the 0.0 version is coming up there. I just fixed this so this fix will be included in release 1.6 and is already in the develop branch.
