### ISSUE TITLE
Make Fails on Ubuntu 12.04.5 LTS

### ISSUE THREAD

**Issue by jpoling-dswrx** [BayshoreNetworks/yextend#2]
Kernel version 3.11.0-15-generic.

Just installed Yara 3.4.0 per the doc's here: http://yara.readthedocs.org/en/latest/gettingstarted.html 

I can get through the yextend install up until make, then the following occurs:

>~/yextend$ sudo make
make  all-am
make[1]: Entering directory `/home/sansforensics/yextend'
g++  -g -O2   -o yextend filedissect.o wrapper.o bayshore_content_scan.o filedata.o main.o zl.o bayshore_yara_wrapper.o  -lpcrecpp -lz -lyara -lcrypto -larchive 
bayshore_content_scan.o: In function `scan_content(unsigned char const*, unsigned long, char const*, std::list<security_scan_results_t, std::allocator<security_scan_results_t> >*, char const*, void (*)(void*, std::list<security_scan_results_t, std::allocator<security_scan_results_t> >*, char const*), int)':
/home/sansforensics/yextend/bayshore_content_scan.cpp:586: undefined reference to `yr_rules_destroy'
main.o: In function `main':
/home/sansforensics/yextend/main.cpp:379: undefined reference to `yr_rules_destroy'
bayshore_yara_wrapper.o: In function `bayshore_yara_preprocess_rules':
/home/sansforensics/yextend/bayshore_yara_wrapper.c:271: undefined reference to `yr_rules_load'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:286: undefined reference to `yr_compiler_create'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:331: undefined reference to `yr_finalize'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:288: undefined reference to `yr_compiler_set_callback'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:319: undefined reference to `yr_compiler_add_file'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:328: undefined reference to `yr_compiler_destroy'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:279: undefined reference to `yr_finalize'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:322: undefined reference to `yr_compiler_get_rules'
bayshore_yara_wrapper.o: In function `bayshore_yara_wrapper_yrrules_api':
/home/sansforensics/yextend/bayshore_yara_wrapper.c:362: undefined reference to `yr_initialize'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:364: undefined reference to `yr_rules_scan_mem'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:378: undefined reference to `yr_finalize'
bayshore_yara_wrapper.o: In function `bayshore_yara_wrapper_api':
/home/sansforensics/yextend/bayshore_yara_wrapper.c:430: undefined reference to `yr_initialize'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:431: undefined reference to `yr_rules_load'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:443: undefined reference to `yr_compiler_create'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:458: undefined reference to `yr_compiler_define_integer_variable'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:465: undefined reference to `yr_compiler_define_boolean_variable'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:506: undefined reference to `yr_compiler_get_rules'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:507: undefined reference to `yr_compiler_destroy'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:517: undefined reference to `yr_rules_scan_mem'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:531: undefined reference to `yr_rules_destroy'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:532: undefined reference to `yr_finalize'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:472: undefined reference to `yr_compiler_define_string_variable'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:482: undefined reference to `yr_compiler_set_callback'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:494: undefined reference to `yr_compiler_add_file'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:500: undefined reference to `yr_compiler_destroy'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:501: undefined reference to `yr_finalize'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:436: undefined reference to `yr_finalize'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:488: undefined reference to `yr_compiler_destroy'
/home/sansforensics/yextend/bayshore_yara_wrapper.c:489: undefined reference to `yr_finalize'
collect2: ld returned 1 exit status
make[1]: *** [yextend] Error 1
make[1]: Leaving directory `/home/sansforensics/yextend'
make: *** [all] Error 2

Any idears?

**Comment by ceelias** [comment]
Can you post your results for the following commands:
1. ls -las /usr/local/lib/libyara.*

2. Use this command to find correct path: sudo find / -name ahocorasick.h -print
    Using that path run this command(example path): ls -las /usr/include/yara 

3. yara -v

**Comment by jpoling-dswrx** [comment]
~/yextend$ ls -las /usr/local/lib/libyara.*
532 -rw-r--r-- 1 root root 543060 Aug 24 18:49 /usr/local/lib/libyara.a
  4 -rwxr-xr-x 1 root root    961 Aug 24 18:49 /usr/local/lib/libyara.la
  0 lrwxrwxrwx 1 root root     16 Aug 24 18:49 /usr/local/lib/libyara.so -> libyara.so.3.4.0
  0 lrwxrwxrwx 1 root root     16 Aug 24 18:49 /usr/local/lib/libyara.so.3 -> libyara.so.3.4.0
308 -rwxr-xr-x 1 root root 313135 Aug 24 18:49 /usr/local/lib/libyara.so.3.4.0

/home/user/yara-3.4.0/libyara/include/yara/ahocorasick.h
/usr/local/include/yara/ahocorasick.h

~/yextend$ yara -v
yara 3.4.0

**Comment by ceelias** [comment]
Can you run(and print results): ls -las /usr/local/include/yara

**Comment by jpoling-dswrx** [comment]
Apologies for forgetting that part. 

~/yextend$ ls -las /usr/local/include/yara
total 116
 4 drwxr-xr-x 2 root root  4096 Aug 24 18:49 .
 4 drwxr-xr-x 4 root root  4096 Aug 24 18:49 ..
 4 -rw-r--r-- 1 root root  1161 Aug 24 18:49 ahocorasick.h
 4 -rw-r--r-- 1 root root  2524 Aug 24 18:49 arena.h
 4 -rw-r--r-- 1 root root  1784 Aug 24 18:49 atoms.h
 8 -rw-r--r-- 1 root root  4635 Aug 24 18:49 compiler.h
 4 -rw-r--r-- 1 root root  3521 Aug 24 18:49 error.h
 8 -rw-r--r-- 1 root root  5232 Aug 24 18:49 exec.h
 4 -rw-r--r-- 1 root root  1531 Aug 24 18:49 filemap.h
 4 -rw-r--r-- 1 root root  1318 Aug 24 18:49 hash.h
 4 -rw-r--r-- 1 root root  1163 Aug 24 18:49 libyara.h
 4 -rw-r--r-- 1 root root  1435 Aug 24 18:49 limits.h
12 -rw-r--r-- 1 root root 10097 Aug 24 18:49 modules.h
 4 -rw-r--r-- 1 root root  2980 Aug 24 18:49 object.h
 8 -rw-r--r-- 1 root root  4877 Aug 24 18:49 re.h
 4 -rw-r--r-- 1 root root  3207 Aug 24 18:49 rules.h
 4 -rw-r--r-- 1 root root   968 Aug 24 18:49 scan.h
 4 -rw-r--r-- 1 root root  1078 Aug 24 18:49 sizedstr.h
 4 -rw-r--r-- 1 root root  1218 Aug 24 18:49 stream.h
 4 -rw-r--r-- 1 root root  1389 Aug 24 18:49 strutils.h
12 -rw-r--r-- 1 root root 10211 Aug 24 18:49 types.h
 4 -rw-r--r-- 1 root root  1403 Aug 24 18:49 utils.h

**Comment by ceelias** [comment]
No problem.
How about:
autoconf -V

**Comment by jpoling-dswrx** [comment]
I recently forced an upgrade to 2.69 because I was getting issues with 2.68 with the configure of yextend.

**Comment by jpoling-dswrx** [comment]
Any ideas?

**Comment by ceelias** [comment]
I created a VM on VirtualBox of Ubuntu 12.04.5 LTS. I first installed Yara given the directions:
http://yara.readthedocs.org/en/latest/gettingstarted.html
I then pulled yextend and followed the readme file. I initially had trouble updating autoreconf to 2.69 which was causing a make failure. Once I updated autoreconf to 2.69, I was able to successfully make and run the test script given in the readme file. 

Are you able to run ./autogen.sh and ./configure succesfully?

**Comment by jpoling-dswrx** [comment]
That is how things went for me as well. I am able to run those commands successfully. However, it fails with the provided errors upon issuing the "make".

**Comment by jpoling-dswrx** [comment]
Any updates?

**Comment by btaub** [comment]
You could try to run make clean and then repeat the yextend quickstart
steps again:

  ./autogen.sh
  ./configure
  ./make

Hopefully this should help.

**Comment by jpoling-dswrx** [comment]
Nope. Same errors.

**Comment by ceelias** [comment]
I set up and ran yextend with no issue on the same version of Linux. At this point I am unable to replicate the behavior you are encountering.

**Comment by jpoling-dswrx** [comment]
Ok, I appreciate your efforts.
