### ISSUE TITLE
Does not find yara.h even with libyara3

### ISSUE THREAD

**Issue by DanielRuf** [BayshoreNetworks/yextend#28]
https://travis-ci.com/DanielRuf/clamav-test/jobs/186282650#L441

Not sure why. What am I missing?

**Comment by DanielRuf** [comment]
Seems `libyara-dev` solved this but now it does not find `archive.h`.

**Comment by DanielRuf** [comment]
Hm, now it works so far but does not find the defined constants from error.h of Yara.

See https://travis-ci.com/DanielRuf/clamav-test/jobs/186338023#L522 until https://travis-ci.com/DanielRuf/clamav-test/jobs/186338023#L539

**Comment by DanielRuf** [comment]
Looks better now but `TRUE` and `FALSE` are problematic.
Anything else that I need?

https://travis-ci.com/DanielRuf/clamav-test/jobs/186361706#L826

**Comment by adamfilipczyk** [comment]
> 
> 
> Looks better now but `TRUE` and `FALSE` are problematic.
> Anything else that I need?
> 
> https://travis-ci.com/DanielRuf/clamav-test/jobs/186361706#L826

Hey Daniel, Did you solve the problem with the FALSE / TRUE related to the show_strings and show_module_data? I cannot figure out why the compiler is looking for these ones within the function while they are declared globaly at the top of the bayshore_yara_wrapper.c

**Comment by DanielRuf** [comment]
> Hey Daniel, Did you solve the problem with the FALSE / TRUE related to the show_strings and show_module_data?

No, I could not find a working solution. See the last build: https://travis-ci.com/DanielRuf/clamav-test/jobs/197786644

**Comment by adamfilipczyk** [comment]
> 
> 
> > Hey Daniel, Did you solve the problem with the FALSE / TRUE related to the show_strings and show_module_data?
> 
> No, I could not find a working solution. See the last build: https://travis-ci.com/DanielRuf/clamav-test/jobs/197786644

Thanks, yeah. I got stuck in the same point

**Comment by JoseGodinez** [comment]
It is fixed in develop branch. Next release 1.7 includes it

**Comment by JoseGodinez** [comment]
I have a build with these dependencies
`	linux-vdso.so.1 (0x00007fffc017e000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f91ea002000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f91e9dfd000)
	libpcrecpp.so.0 => /usr/lib/x86_64-linux-gnu/libpcrecpp.so.0 (0x00007f91e9bf3000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f91e99d9000)
	libyara.so.3 => /opt/singlekey/image/3rdparty/lib/libyara.so.3 (0x00007f91e9787000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f91e92ee000)
	libarchive.so.13 => /usr/lib/x86_64-linux-gnu/libarchive.so.13 (0x00007f91e903a000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f91e8cb8000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f91e89b4000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f91e879d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f91e83fe000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f91ea56a000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f91e818b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f91e7f6e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f91e7d6a000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f91e7b33000)
	libacl.so.1 => /lib/x86_64-linux-gnu/libacl.so.1 (0x00007f91e792a000)
	liblzo2.so.2 => /lib/x86_64-linux-gnu/liblzo2.so.2 (0x00007f91e7708000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f91e74e2000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f91e72d0000)
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f91e6f15000)
	libattr.so.1 => /lib/x86_64-linux-gnu/libattr.so.1 (0x00007f91e6d10000)
	libicui18n.so.57 => /usr/lib/x86_64-linux-gnu/libicui18n.so.57 (0x00007f91e6896000)
	libicuuc.so.57 => /usr/lib/x86_64-linux-gnu/libicuuc.so.57 (0x00007f91e64ee000)
	libicudata.so.57 => /usr/lib/x86_64-linux-gnu/libicudata.so.57 (0x00007f91e4a71000)
`
Probably you need 
apt-get install libpcre3-dev libarchive-dev libbz2-dev libssl-dev

**Comment by JoseGodinez** [comment]
> > > Hey Daniel, Did you solve the problem with the FALSE / TRUE related to the show_strings and show_module_data?
> > 
> > 
> > No, I could not find a working solution. See the last build: https://travis-ci.com/DanielRuf/clamav-test/jobs/197786644
> 
> Thanks, yeah. I got stuck in the same point

TRUE | FALSE issues are fixed in yara-3.9.0 branch

**Comment by JoseGodinez** [comment]
https://travis-ci.org/BayshoreNetworks/yextend/builds/612255509
