### ISSUE TITLE
Yextend error.

### ISSUE THREAD

**Issue by namanitta** [BayshoreNetworks/yextend#3]
I am preparing my machine for malware analysis and I am getting this error at make:
=================================
make  all-am
make[1]: Entering directory `/home/cuckoo/yextend-1.2'
g++ -DHAVE_CONFIG_H -I.   -I.  -g -O2 -MT bayshore_content_scan.o -MD -MP -MF .deps/bayshore_content_scan.Tpo -c -o bayshore_content_scan.o bayshore_content_scan.cpp
bayshore_content_scan.cpp: In function ‘void scan_office_open_xml_api(void*, std::list<security_scan_results_t>*, const char*, const char*, bool, void (*)(void*, std::list<security_scan_results_t>*, const char*), int)’:
bayshore_content_scan.cpp:303:61: error: cannot convert ‘off_t* {aka long int*}’ to ‘int64_t* {aka long long int*}’ for argument ‘4’ to ‘int archive_read_data_block(archive*, const void**, size_t*, int64_t*)’
        x = archive_read_data_block(a, &buff, &lsize, &offset);
                                                             ^
bayshore_content_scan.cpp: In function ‘void scan_content2(const uint8_t*, size_t, YR_RULES*, std::list<security_scan_results_t>*, const char*, void (*)(void*, std::list<security_scan_results_t>*, const char*), int)’:
bayshore_content_scan.cpp:749:62: error: cannot convert ‘off_t* {aka long int*}’ to ‘int64_t* {aka long long int*}’ for argument ‘4’ to ‘int archive_read_data_block(archive*, const void**, size_t*, int64_t*)’
         x = archive_read_data_block(a, &buff, &lsize, &offset);
                                                              ^
make[1]: *** [bayshore_content_scan.o] Error 1
make[1]: Leaving directory `/home/cuckoo/yextend-1.2'
make: *** [all] Error 2
===================================
any help?
thank you

**Comment by dre** [comment]
What OS (and bitness) are you running on?

**Comment by namanitta** [comment]
My OS is debian Mint 17.1 and the bitness is 64. Thank you.

**Comment by anamanya** [comment]
Hi! Any help regarding this yet?

**Comment by ceelias** [comment]
I have set up a VM matching your environment. I went through the process of setting up Yara and yextend and I was unable to replicate your error.
