### ISSUE TITLE
Update minimum Yara version

### ISSUE THREAD

**Issue by cecobayshore** [BayshoreNetworks/yextend#30]
yextend will require Yara 3.6 and above.
Change code to check for: YR_MAJOR_VERSION == 3 && YR_MINOR_VERSION >= 6
Update README to reflect the requirements.

**Comment by JoseGodinez** [comment]
`YEXTEND_VERSION >= 1.2 && yara_major_minor_version.first <= 3 && yara_major_minor_version.second < 6)`
