### ISSUE TITLE
Invalid yara version detected?

### ISSUE THREAD

**Issue by willdurand** [BayshoreNetworks/yextend#32]
`yextend` misreads the `yara` version when the minor number is greater than `9`, it seems. My current `yara` version is `3.10.0` and not `3.1`:

```
Version issue: yextend version 1.7+ will not run with yara versions below 3.4

Your env has yextend version 1.7
Your env has yara version 3.1
```

```
$ yara -v
3.10.0
```

**Comment by cecobayshore** [comment]
Try branch 'yara-3.9.0' - despite the name, it should be using Yara 3.10.0.
Development docker containers can be built as well. Take a look inside 'dockerize' folder.

**Comment by willdurand** [comment]
Hi, thanks for your comment. I am not sure to understand how switching to the `yara-3.9.0` branch would help. I don't see where the `yextend` code has been changed to correctly infer the right version in this branch.

I'll compile the version from `yara-3.9.0` and retry but I think I'm missing something. I have the feeling that the `yextend` version parsing isn't working as intended (because it uses a string to float function).

**Comment by mrcbax** [comment]
my hacky patch. replace this function in main.cpp and recompile. The program thinks the version is 3.9.0 now. just be aware of the minimum version for yara when you go to use this and update if need be.
```c++
double get_yara_version() {

	/*
	 * older versions of yara seem to output version like this:
	 *
	 * yara 3.4.0
	 *
	 * while the later ones just do:
	 *
	 * 3.6.0
	 *
	 */
	FILE *fp;
	double yara_version = 0.0;
	char yver[10];
	std::string y = "yara";
	std::string yver_str;

	fp = popen("yara -v", "r");
	if (fp != NULL) {

		if (fgets (yver, sizeof(yver)-1, fp) != NULL) {

			yver_str = "3.9.0";
			std::size_t found = yver_str.find(y);
			if (found != std::string::npos) {
				yver_str = yver_str.substr(found + 5);
			}

			//yara_version = strtod(yver, NULL);
			yara_version = strtod(yver_str.c_str(), NULL);

		}

		pclose(fp);

	}

	return yara_version;
}
```

**Comment by JoseGodinez** [comment]
`# yara --version
3.11.0
`
`# ./yextend -r test_rulesets/pdf_multiple_embed.yara -t test_files/OPCUA.pdf -j
[
    {
        "file_name": "test_files/OPCUA.pdf",
        "file_signature_MD5": "2554761787a0578c0f916fa5e32f29a5",
        "file_size": 90219,
        "scan_results": [
            {
                "file_signature_MD5": "2554761787a0578c0f916fa5e32f29a5",
                "file_size": 90219,
                "non_archive_file_name": "test_files/OPCUA.pdf",
                "scan_type": "Yara Scan (PDF - Raw data)",
                "yara_matches_found": false
            },
            {
                "file_signature_MD5": "344a4366790a22f98876a9eb5209f43e",
                "file_size": 478,
                "non_archive_file_name": "test_files/OPCUA.pdf",
                "scan_type": "Yara Scan (PDF - Extracted text)",
                "yara_matches_found": false
            }
        ],
        "yara_ruleset_file_name": "test_rulesets/pdf_multiple_embed.yara"
    }
]`

**Comment by JoseGodinez** [comment]
Fixed
