### ISSUE TITLE
Exception when using run_yextend to run a ruleset on a pdf file

### ISSUE THREAD

**Issue by spal-bayshorenetworks** [BayshoreNetworks/yextend#6]
Exception when using run_yextend to run a ruleset on a pdf file

Traceback (most recent call last):
  File "./run_yextend", line 169, in <module>
    print_yextend_output(out=out)
  File "./run_yextend", line 120, in print_yextend_output
    rmdspl_offset, rmdspl_label = rmdspl.split(':')
ValueError: need more than 1 value to unpack
[Fermilab.pdf](https://github.com/BayshoreNetworks/yextend/files/382344/Fermilab.pdf)

**Comment by dre** [comment]
Fixed - b847daa
