### ISSUE TITLE
yextend 1.5 version is not detecting .avi file.

### ISSUE THREAD

**Issue by spal-bayshorenetworks** [BayshoreNetworks/yextend#8]
In yextend 1.4, we were detecting it correctly (Audio Video Interleaved File (AVI)). But in 1.5, we are detecting it as encrypted file.

Command to run:

./run_yextend test_rulesets/bayshore.yara.testing.ruleset test_files/sample.avi

**Comment by dre** [comment]
Fixed in commit 02178ba8 (develop branch until this is merged into master)
